# SXMXDX - SPRING BOOT

spring.application.name=sxmxdx-backend

server.port=8080


# POSTGRESQL

spring.datasource.url=jdbc:postgresql://${DB_HOST:postgresSimp}:${DB_PORT:5432}/${DB_NAME:sxmxdx2}

spring.datasource.username=${DB_USER:sxmxdx}

spring.datasource.password=${DB_PASSWORD:diary}

spring.datasource.driver-class-name=org.postgresql.Driver


# JPA / HIBERNATE

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=none

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB


pipeline.api.url=${PIPELINE_API_URL:http://spark:5000}